/* Gnuplots data generated by vary-n, vary-k, or vary-d */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv)
{
	FILE* fp;
	char command[256];
	if (argc < 4 or argc > 5)
	{
		printf("usage: makeplot [N|D|K|db|M] input-file output-file \n");
		printf("Or usage: makeplot [N|D|K] input-file output-file time \n");
		return 0;
	}

	fp = fopen("plot.p", "w");

	fprintf(fp, "set term postscript eps color\n");
	fprintf(fp, "set output \"%s.eps\"\n", argv[3]);
	fprintf(fp, "set xlabel '%s'\n", argv[1]);

	if (argc == 5)
		fprintf(fp, "set ylabel 'Time (seconds)'\n");
	else
		fprintf(fp, "set ylabel 'Maximum regret ratio'\n");


	fprintf(fp, "set key left top\n");

	fprintf(fp, "set key box\n");
	fprintf(fp, "set size .5,.5\n");


	if (argv[1][0] == 'd' || argv[1][0] == 'D')
		fprintf(fp, "set xtic 1\n");

	if (argv[1][0] == 'n' || argv[1][0] == 'N')
        	fprintf(fp, "set logscale x\n");

  	if (argv[1][0] == 'm' || argv[1][0] == 'M')
        	fprintf(fp, "set logscale x\n");

	if (argc == 5)
  {
    fprintf(fp, "set logscale y\n");
    fprintf(fp, "plot \"%s\" using 1:(100*$8) title 'Cube' with linespoints lw 2, \"%s\" using 1:(100*$9) title 'Sphere' with linespoints lw 2, \"%s\" using 1:(100*$10) title 'ImpGreedy' with linespoints lw 2", argv[2], argv[2], argv[2]);
  }
	else
	{
	  fprintf(fp, "set yrange [0:*]\n");
	  fprintf(fp, "set format y \"%s\"\n", "\%2.0f\%\%");
		fprintf(fp, "plot \"%s\" using 1:(100*$2) title 'Cube' with linespoints lw 2, \"%s\" using 1:(100*$3) title 'Cube LIB' with linespoints lw 2, \"%s\" using 1:(100*$4) title 'Sphere' with linespoints lw 2, \"%s\" using 1:(100*$5) title 'Sphere LIB' with linespoints lw 2, \"%s\" using 1:(100*$6) title 'Imp Greedy' with linespoints lw 2, \"%s\" using 1:(100*$7) title 'Imp Greedy LIB' with linespoints lw 2\n", argv[2], argv[2], argv[2], argv[2],argv[2],argv[2]);
	}

	fclose(fp);
	system("gnuplot plot.p");

	sprintf(command, "convert %s.eps %s.jpg" , argv[3], argv[3]);
	system(command);

	//system("rm plot.p");

	return 0;
}
